AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  github-packages-proxy
  A seamless proxy for GitHub Packages

Globals:
  Function:
    Timeout: 3

Resources:
  maven:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          GITHUB_USER: !Ref GITHUB_USER
          GITHUB_TOKEN: !Ref GITHUB_TOKEN
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - lambda.ts